<?php

namespace Sysborg\FocusNfe\app\DTO;

use Illuminate\Support\Facades\Validator;
use Illuminate\Validation\ValidationException;

class EmpresaDTO extends DTO
{
    public function __construct(
        public string $razaoSocial,
        public string $nomeFantasia,
        public string $bairro,
        public int $cep,
        public string $cnpj,
        public string $complemento,
        public string $email,
        public string $inscricaoEstadual,
        public string $inscricaoMunicipal,
        public string $logradouro,
        public int $numero,
        public int $regimeTributario,
        public string $telefone,
        public string $municipio,
        public string $uf,
        public bool $habilitaNfe,
        public bool $habilitaNfce,
        public bool $habilitaNfse,
        public string $arquivoCertificado,
        public string $senhaCertificado,
        public string $cscNfceProducao,
        public string $idTokenNfceProducao,
        public bool $enviaEmailDestinatario = true,
        public bool $discriminaImposto = true,
        public bool $certificadoEspecifico = false,
        public ?string $cpfCnpjContabilidade = null,
        public bool $habilitaNfsenProducao = false,
        public bool $habilitaNfsenHomologacao = false,
        public bool $habilitaNfsenRecebidasProducao = false,
        public bool $habilitaNfsenRecebidasHomologacao = false,
        public bool $habilitaCte = false,
        public bool $habilitaMdfe = false,
        public bool $habilitaManifestacao = false,
        public bool $habilitaManifestacaoCte = false,
        public bool $habilitaContingenciaOfflineNfce = false,
        public bool $reaproveitaNumeroNfceContingencia = false,
        public bool $mostrarDanfseBadge = false,
        public ?string $orientacaoDanfe = null,
        public bool $reciboDanfe = false,
        public bool $exibeSempreIpiDanfe = false,
        public bool $exibeIssqnDanfe = false,
        public bool $exibeImpostosAdicionaisDanfe = false,
        public bool $exibeUnidadeTributariaDanfe = false,
        public bool $exibeSempreVolumesDanfe = false,
        public bool $exibeComposicaoCargaMdfe = false,
        public bool $enviarEmailHomologacao = false,
        public ?string $cscNfceHomologacao = null,
        public ?string $idTokenNfceHomologacao = null,
        public ?int $proximoNumeroNfseProducao = null,
        public ?int $proximoNumeroNfseHomologacao = null,
        public ?int $serieNfseProducao = null,
        public ?int $serieNfseHomologacao = null,
        public ?int $proximoNumeroNfsenProducao = null,
        public ?int $proximoNumeroNfsenHomologacao = null,
        public ?int $serieNfsenProducao = null,
        public ?int $serieNfsenHomologacao = null,
        public ?int $proximoNumeroNfeProducao = null,
        public ?int $proximoNumeroNfeHomologacao = null,
        public ?int $serieNfeProducao = null,
        public ?int $serieNfeHomologacao = null,
        public ?int $proximoNumeroNfceProducao = null,
        public ?int $proximoNumeroNfceHomologacao = null,
        public ?int $serieNfceProducao = null,
        public ?int $serieNfceHomologacao = null,
        public ?int $proximoNumeroCteProducao = null,
        public ?int $proximoNumeroCteHomologacao = null,
        public ?int $serieCteProducao = null,
        public ?int $serieCteHomologacao = null,
        public ?int $proximoNumeroCteOsProducao = null,
        public ?int $proximoNumeroCteOsHomologacao = null,
        public ?int $serieCteOsProducao = null,
        public ?int $serieCteOsHomologacao = null,
        public ?int $proximoNumeroMdfeProducao = null,
        public ?int $proximoNumeroMdfeHomologacao = null,
        public ?int $serieMdfeProducao = null,
        public ?int $serieMdfeHomologacao = null,
        public bool $nfeSincrono = false,
        public bool $nfeSincronoHomologacao = false,
        public bool $mdfeSincrono = false,
        public bool $mdfeSincronoHomologacao = false,
    ) {
        $this->validate();
    }

    protected static function fieldMapping(): array
    {
        return [
            'razaoSocial' => 'nome',
            'arquivoCertificado' => 'arquivo_certificado_base64',
            'enviaEmailDestinatario' => 'enviar_email_destinatario',
            'discriminaImposto' => 'discrimina_impostos',
            'idTokenNfceProducao' => 'id_token_nfce_producao',
            'idTokenNfceHomologacao' => 'id_token_nfce_homologacao',
        ];
    }

    protected function validate(): void
    {
        $validator = Validator::make(get_object_vars($this), self::rules(), self::messages());

        if ($validator->fails()) {
            throw new ValidationException($validator);
        }
    }

    public static function rules(): array
    {
        return [
            'razaoSocial' => 'required|string|max:255',
            'cnpj' => 'required|cnpj',
            'email' => 'required|email|max:255',
            'bairro' => 'required|string|max:100',
            'cep' => 'required|integer',
            'logradouro' => 'required|string|max:255',
            'numero' => 'required|integer|min:0',
            'municipio' => 'required|string|max:100',
            'uf' => 'required|string|size:2',
            'regimeTributario' => 'required|integer|between:1,4',
            'telefone' => 'required|string|max:20',
            'habilitaNfe' => 'required|boolean',
            'habilitaNfce' => 'required|boolean',
            'habilitaNfse' => 'required|boolean',
            'enviaEmailDestinatario' => 'boolean',
            'discriminaImposto' => 'boolean',
            'certificadoEspecifico' => 'boolean',
            'cpfCnpjContabilidade' => 'nullable|string|max:18',
            'habilitaNfsenProducao' => 'boolean',
            'habilitaNfsenHomologacao' => 'boolean',
            'habilitaNfsenRecebidasProducao' => 'boolean',
            'habilitaNfsenRecebidasHomologacao' => 'boolean',
            'habilitaCte' => 'boolean',
            'habilitaMdfe' => 'boolean',
            'habilitaManifestacao' => 'boolean',
            'habilitaManifestacaoCte' => 'boolean',
            'habilitaContingenciaOfflineNfce' => 'boolean',
            'reaproveitaNumeroNfceContingencia' => 'boolean',
            'mostrarDanfseBadge' => 'boolean',
            'orientacaoDanfe' => 'nullable|string|in:portrait,landscape,ladscape',
            'reciboDanfe' => 'boolean',
            'exibeSempreIpiDanfe' => 'boolean',
            'exibeIssqnDanfe' => 'boolean',
            'exibeImpostosAdicionaisDanfe' => 'boolean',
            'exibeUnidadeTributariaDanfe' => 'boolean',
            'exibeSempreVolumesDanfe' => 'boolean',
            'exibeComposicaoCargaMdfe' => 'boolean',
            'enviarEmailHomologacao' => 'boolean',
            'cscNfceProducao' => 'required_if:habilitaNfce,true|string|max:100',
            'idTokenNfceProducao' => 'required_if:habilitaNfce,true|string|max:10',
            'cscNfceHomologacao' => 'nullable|string|max:100',
            'idTokenNfceHomologacao' => 'nullable|string|max:10',
            'arquivoCertificado' => 'required_if:certificadoEspecifico,true|string',
            'senhaCertificado' => 'required_if:certificadoEspecifico,true|string|max:100',
            'nomeFantasia' => 'required|string|max:255',
            'complemento' => 'nullable|string|max:100',
            'inscricaoEstadual' => 'required_if:habilitaNfe,true|required_if:habilitaNfce,true|nullable|string|max:20',
            'inscricaoMunicipal' => 'required_if:habilitaNfse,true|string|max:20',
            'proximoNumeroNfseProducao' => 'nullable|integer|min:1',
            'proximoNumeroNfseHomologacao' => 'nullable|integer|min:1',
            'serieNfseProducao' => 'nullable|integer|min:1',
            'serieNfseHomologacao' => 'nullable|integer|min:1',
            'proximoNumeroNfsenProducao' => 'nullable|integer|min:1',
            'proximoNumeroNfsenHomologacao' => 'nullable|integer|min:1',
            'serieNfsenProducao' => 'nullable|integer|min:1',
            'serieNfsenHomologacao' => 'nullable|integer|min:1',
            'proximoNumeroNfeProducao' => 'nullable|integer|min:1',
            'proximoNumeroNfeHomologacao' => 'nullable|integer|min:1',
            'serieNfeProducao' => 'nullable|integer|min:1',
            'serieNfeHomologacao' => 'nullable|integer|min:1',
            'proximoNumeroNfceProducao' => 'nullable|integer|min:1',
            'proximoNumeroNfceHomologacao' => 'nullable|integer|min:1',
            'serieNfceProducao' => 'nullable|integer|min:1',
            'serieNfceHomologacao' => 'nullable|integer|min:1',
            'proximoNumeroCteProducao' => 'nullable|integer|min:1',
            'proximoNumeroCteHomologacao' => 'nullable|integer|min:1',
            'serieCteProducao' => 'nullable|integer|min:1',
            'serieCteHomologacao' => 'nullable|integer|min:1',
            'proximoNumeroCteOsProducao' => 'nullable|integer|min:1',
            'proximoNumeroCteOsHomologacao' => 'nullable|integer|min:1',
            'serieCteOsProducao' => 'nullable|integer|min:1',
            'serieCteOsHomologacao' => 'nullable|integer|min:1',
            'proximoNumeroMdfeProducao' => 'nullable|integer|min:1',
            'proximoNumeroMdfeHomologacao' => 'nullable|integer|min:1',
            'serieMdfeProducao' => 'nullable|integer|min:1',
            'serieMdfeHomologacao' => 'nullable|integer|min:1',
            'nfeSincrono' => 'boolean',
            'nfeSincronoHomologacao' => 'boolean',
            'mdfeSincrono' => 'boolean',
            'mdfeSincronoHomologacao' => 'boolean',
        ];
    }

    public static function messages(): array
    {
        return [
            'razaoSocial.required' => 'A razão social é obrigatória',
            'razaoSocial.string' => 'A razão social deve ser um texto',
            'razaoSocial.max' => 'A razão social não pode ter mais de 255 caracteres',
            'cnpj.required' => 'O CNPJ é obrigatório',
            'cnpj.cnpj' => 'O CNPJ informado é inválido',
            'email.required' => 'O email é obrigatório',
            'email.email' => 'O email informado é inválido',
            'email.max' => 'O email não pode ter mais de 255 caracteres',
            'bairro.required' => 'O bairro é obrigatório',
            'bairro.max' => 'O bairro não pode ter mais de 100 caracteres',
            'cep.required' => 'O CEP é obrigatório',
            'cep.integer' => 'O CEP deve ser numérico',
            'logradouro.required' => 'O logradouro é obrigatório',
            'logradouro.max' => 'O logradouro não pode ter mais de 255 caracteres',
            'numero.required' => 'O número é obrigatório',
            'numero.integer' => 'O número deve ser numérico',
            'numero.min' => 'O número deve ser maior ou igual a zero',
            'complemento.max' => 'O complemento não pode ter mais de 100 caracteres',
            'municipio.required' => 'O município é obrigatório',
            'municipio.max' => 'O município não pode ter mais de 100 caracteres',
            'uf.required' => 'A UF é obrigatória',
            'uf.size' => 'A UF deve ter exatamente 2 caracteres',
            'regimeTributario.required' => 'O regime tributário é obrigatório',
            'regimeTributario.integer' => 'O regime tributário deve ser numérico',
            'regimeTributario.between' => 'O regime tributário deve ser 1 (Simples Nacional), 2 (Simples Nacional - excesso), 3 (Regime Normal) ou 4 (MEI)',
            'telefone.required' => 'O telefone é obrigatório',
            'telefone.max' => 'O telefone não pode ter mais de 20 caracteres',
            'inscricaoEstadual.max' => 'A inscrição estadual não pode ter mais de 20 caracteres',
            'inscricaoMunicipal.max' => 'A inscrição municipal não pode ter mais de 20 caracteres',
            'cscNfceProducao.required_if' => 'O CSC de produção é obrigatório quando NFCe está habilitada',
            'cscNfceProducao.max' => 'O CSC não pode ter mais de 100 caracteres',
            'idTokenNfceProducao.required_if' => 'O ID Token de produção é obrigatório quando NFCe está habilitada',
            'idTokenNfceProducao.max' => 'O ID Token não pode ter mais de 10 caracteres',
            'arquivoCertificado.required_if' => 'O arquivo do certificado é obrigatório quando certificado específico está habilitado',
            'senhaCertificado.required_if' => 'A senha do certificado é obrigatória quando certificado específico está habilitado',
            'senhaCertificado.max' => 'A senha do certificado não pode ter mais de 100 caracteres',
        ];
    }

    public static function fromArray(array $data): self
    {
        return new self(
            $data['razaoSocial'],
            $data['nomeFantasia'] ?? '',
            $data['bairro'],
            $data['cep'],
            $data['cnpj'],
            $data['complemento'] ?? '',
            $data['email'],
            $data['inscricaoEstadual'] ?? '',
            $data['inscricaoMunicipal'] ?? '',
            $data['logradouro'],
            $data['numero'],
            $data['regimeTributario'],
            $data['telefone'],
            $data['municipio'],
            $data['uf'],
            $data['habilitaNfe'],
            $data['habilitaNfce'],
            $data['habilitaNfse'] ?? false,
            $data['arquivoCertificado'] ?? '',
            $data['senhaCertificado'] ?? '',
            $data['cscNfceProducao'] ?? '',
            $data['idTokenNfceProducao'] ?? '',
            $data['enviaEmailDestinatario'] ?? true,
            $data['discriminaImposto'] ?? true,
            $data['certificadoEspecifico'] ?? false,
            $data['cpfCnpjContabilidade'] ?? null,
            $data['habilitaNfsenProducao'] ?? false,
            $data['habilitaNfsenHomologacao'] ?? false,
            $data['habilitaNfsenRecebidasProducao'] ?? false,
            $data['habilitaNfsenRecebidasHomologacao'] ?? false,
            $data['habilitaCte'] ?? false,
            $data['habilitaMdfe'] ?? false,
            $data['habilitaManifestacao'] ?? false,
            $data['habilitaManifestacaoCte'] ?? false,
            $data['habilitaContingenciaOfflineNfce'] ?? false,
            $data['reaproveitaNumeroNfceContingencia'] ?? false,
            $data['mostrarDanfseBadge'] ?? false,
            $data['orientacaoDanfe'] ?? null,
            $data['reciboDanfe'] ?? false,
            $data['exibeSempreIpiDanfe'] ?? false,
            $data['exibeIssqnDanfe'] ?? false,
            $data['exibeImpostosAdicionaisDanfe'] ?? false,
            $data['exibeUnidadeTributariaDanfe'] ?? false,
            $data['exibeSempreVolumesDanfe'] ?? false,
            $data['exibeComposicaoCargaMdfe'] ?? false,
            $data['enviarEmailHomologacao'] ?? false,
            $data['cscNfceHomologacao'] ?? null,
            $data['idTokenNfceHomologacao'] ?? null,
            $data['proximoNumeroNfseProducao'] ?? null,
            $data['proximoNumeroNfseHomologacao'] ?? null,
            $data['serieNfseProducao'] ?? null,
            $data['serieNfseHomologacao'] ?? null,
            $data['proximoNumeroNfsenProducao'] ?? null,
            $data['proximoNumeroNfsenHomologacao'] ?? null,
            $data['serieNfsenProducao'] ?? null,
            $data['serieNfsenHomologacao'] ?? null,
            $data['proximoNumeroNfeProducao'] ?? null,
            $data['proximoNumeroNfeHomologacao'] ?? null,
            $data['serieNfeProducao'] ?? null,
            $data['serieNfeHomologacao'] ?? null,
            $data['proximoNumeroNfceProducao'] ?? null,
            $data['proximoNumeroNfceHomologacao'] ?? null,
            $data['serieNfceProducao'] ?? null,
            $data['serieNfceHomologacao'] ?? null,
            $data['proximoNumeroCteProducao'] ?? null,
            $data['proximoNumeroCteHomologacao'] ?? null,
            $data['serieCteProducao'] ?? null,
            $data['serieCteHomologacao'] ?? null,
            $data['proximoNumeroCteOsProducao'] ?? null,
            $data['proximoNumeroCteOsHomologacao'] ?? null,
            $data['serieCteOsProducao'] ?? null,
            $data['serieCteOsHomologacao'] ?? null,
            $data['proximoNumeroMdfeProducao'] ?? null,
            $data['proximoNumeroMdfeHomologacao'] ?? null,
            $data['serieMdfeProducao'] ?? null,
            $data['serieMdfeHomologacao'] ?? null,
            $data['nfeSincrono'] ?? false,
            $data['nfeSincronoHomologacao'] ?? false,
            $data['mdfeSincrono'] ?? false,
            $data['mdfeSincronoHomologacao'] ?? false,
        );
    }
}
